#!/usr/bin/env python3
"""Write macro_text.h, the text typed by each text macro.

Each macro NAME takes its text from $KB_MACRO_<NAME> or, failing that, from
macros/<name>.txt next to this script. Neither the text files nor the
generated header are committed.
"""
import os
import pathlib
import sys

MACROS = ['LCGRIND']

here = pathlib.Path(__file__).resolve().parent

def macro_text(name):
    var, path = f'KB_MACRO_{name}', here / 'macros' / f'{name.lower()}.txt'
    if var in os.environ:
        return os.environ[var], var
    if path.exists():
        return path.read_text().removesuffix('\n'), path.name
    print(f'WARNING: no text for macro {name}, set {var} or create {path}', file=sys.stderr)
    return '', 'nothing'

lines = ['// Generated by macro_text.py, do not commit']
for name in MACROS:
    text, source = macro_text(name)
    bad = sorted({c for c in text if not (' ' <= c <= '~' or c == '\n')})
    if bad:
        sys.exit(f'ERROR: SEND_STRING can only type printable ASCII, not {bad!r} in macro {name}')
    literal = text.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
    lines.append(f'#define MACRO_{name} "{literal}" // from {source}')

header = '\n'.join(lines) + '\n'
out = here / 'macro_text.h'
if not out.exists() or out.read_text() != header:
    out.write_text(header)
